function t232_expandtext(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var text=rec.querySelector('.t232__text');if(!text)return;if(text.style.display==='block'||!text.style.display){text.style.display='none'}else{text.style.display='block'}}
function t448_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var cover=rec.querySelector('.t-cover');var coverHeight=cover?cover.offsetHeight:0;var coverWrapper=rec.querySelector('.t448-cover__wrapper');var textWrapper=rec.querySelector('.t448__wrapper');var textHeight=textWrapper?textWrapper.clientHeight:0;var screenShot=rec.querySelector('.t448__screenshot');var imgHeight=screenShot?screenShot.offsetHeight:0;var height=textHeight+imgHeight;var newHeight=coverHeight-imgHeight;var container=rec.querySelector('.t448');var cropImg=container?container.getAttribute('data-crop-image'):'';if(cropImg&&container){container.classList.add('t448__no-overflow');if(coverWrapper){container.style.height=coverWrapper.offsetHeight+'px'}}
if(coverHeight>height){rec.classList.add('t448__stretched');if(coverWrapper)coverWrapper.style.height=newHeight+'px';if(cropImg&&container){container.classList.remove('t448__no-overflow');container.style.height=''}}else{rec.classList.remove('t448__stretched');if(coverWrapper)coverWrapper.style.height=''}}
function t602_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var indicator=rec.querySelector('.t602__indicator');if(!indicator)return;window.addEventListener('scroll',t_throttle(function(){var documentHeight=document.body.clientHeight;var windowScrollTop=document.documentElement.scrollTop;var windowHeight=window.innerHeight;var scrollPercent=(windowScrollTop/(documentHeight-windowHeight))*100;indicator.style.width=scrollPercent+'%'},100))}
function t678_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t678__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t678__fadeOut(tildaLabel,50)}},300)}else{t678__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t678__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t678__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t678__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t678__easeInOutCubic(currentTime,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t678__animateScroll(){currentTime+=increment;window.scrollTo(0,t678__easeInOutCubic(currentTime,change));if(currentTime<duration){setTimeout(t678__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t678__animateScroll()}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t702_resizePopup(recId);t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup()});popupCloseBtn.addEventListener('click',t702_closePopup);if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var range=rec.querySelector('.t-range');var documentBody=document.body;popup.style.display='block';if(range)t702__triggerEvent(range,'popupOpened');setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
document.addEventListener('keydown',t702_escClosePopup);t702__lazyLoad()}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup()}
function t702_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t702__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t702_escClosePopup)}
function t702_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t702__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t702__fadeOut(tildaLabel)}},300)}else{t702__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t702__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t702__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t702__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t702__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t702__animateScroll(){currentTime+=increment;window.scrollTo(0,t702__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t702__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t702__animateScroll()}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t712_onSuccess(originalForm){var form=originalForm;if(originalForm instanceof jQuery&&originalForm.length){form=originalForm.get(0)}
var inputsWrapper=form.querySelector('.t-form__inputsbox');var successBox=form.querySelector('.t-form__successbox');var inputsWrapperHeight=inputsWrapper?inputsWrapper.offsetHeight:0;var inputsWrapperOffsetTop=inputsWrapper?inputsWrapper.getBoundingClientRect().top+window.pageYOffset:0;var inputsBottom=inputsWrapperHeight+inputsWrapperOffsetTop;var targetOffset=successBox?successBox.getBoundingClientRect().top+window.pageYOffset:0;var targetYoutubeRecommendationsArea=window.innerWidth>960?200:100;var target=targetOffset-targetYoutubeRecommendationsArea;var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(targetOffset>window.pageYOffset||((documentHeight-inputsBottom)<(window.innerHeight-100))){if(inputsWrapper)inputsWrapper.classList.add('t712__inputsbox_hidden');setTimeout(function(){var tBody=document.querySelector('.t-body');if(tBody&&window.innerHeight>tBody.offsetHeight){var tLabel=document.querySelector('.t-tildalabel');if(tLabel){t712_fadeOut(tLabel,50)}}},300)}else{t712_scrollToNextSection(target,400);setTimeout(function(){if(inputsWrapper)inputsWrapper.classList.add('t712__inputsbox_hidden')},400)}
var successurl=form.getAttribute('data-success-url');if(successurl){setTimeout(function(){window.location.href=successurl},500)}}
function t712_fixcontentheight(id){var rec=document.getElementById('rec'+id);if(!rec)return;var cover=rec.querySelector('.t-cover');var filter=rec.querySelector('.t-cover__filter');var carrier=rec.querySelector('.t-cover__carrier');var wrapper=rec.querySelector('.t-cover__wrapper');var container=rec.querySelector('.t-cover__container');var coverHeight=cover?cover.offsetHeight:0;var content=rec.querySelector('div[data-hook-content]');var contentHeight=content?content.offsetHeight:0;if(contentHeight>300&&coverHeight<contentHeight){var youTubeRecommendationsSpace=120;if(contentHeight>1000)youTubeRecommendationsSpace+=100;contentHeight+=youTubeRecommendationsSpace;console.log('auto correct cover height: '+contentHeight);if(cover)cover.style.height=contentHeight+'px';if(filter)filter.style.height=contentHeight+'px';if(carrier)carrier.style.height=contentHeight+'px';if(wrapper)wrapper.style.height=contentHeight+'px';if(container)container.style.height=contentHeight+'px';if(!window.isMobile){setTimeout(function(){var videoBlock=rec.querySelector('.t-cover__carrier');if(videoBlock&&videoBlock.querySelector('iframe')){console.log('correct video from cover_fixcontentheight');window.setWidthAndHeightVideo(videoBlock,contentHeight+'px','youtube')}},2000)}}}
function t712_fadeOut(el,duration){var opacity=1;duration=parseInt(duration);var speed=duration>0?duration/ 10 : 40; /*default duration = 400*/
var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer)}},speed)}
function t712_scrollToNextSection(to,duration){if(duration<=0)return;var difference=to-window.pageYOffset;var perTick=difference/duration*10;setTimeout(function(){window.scrollTo(0,window.pageYOffset+perTick);document.body.setAttribute('data-scrollable','true');if(window.pageYOffset===to){document.body.removeAttribute('data-scrollable');return}
t712_scrollToNextSection(to,duration-10)},10);setTimeout(function(){if(document.body.getAttribute('data-scrollable')==='true'){document.body.removeAttribute('data-scrollable')}},duration*2)}
function t821_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec?rec.querySelector('.t821'):null;if(!menu)return;var isFixed=menu.style.position==='fixed'||window.getComputedStyle(menu).position==='fixed';var isRedactorMode=menu.classList.contains('t821_redactor-mode');if(!isRedactorMode){menu.classList.remove('t821__beforeready');if(isFixed&&menu.getAttribute('data-bgopacity-two')){t821_changebgopacitymenu();window.addEventListener('scroll',t_throttle(function(){t821_changebgopacitymenu()},200))}
if(isFixed&&menu.getAttribute('data-appearoffset')){menu.classList.remove('t821__beforeready');t821_appearMenu();window.addEventListener('scroll',t_throttle(function(){t821_appearMenu()},200))}}
t821_setBg();window.addEventListener('resize',t_throttle(function(){t821_setBg()},200))}
function t821_setBg(){var menuBlocks=document.querySelectorAll('.t821');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t821_appearMenu(){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t821');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t821_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t821_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t821_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t821_changebgopacitymenu(){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t821');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t821_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t821');var burger=rec.querySelector('.t821__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t821_opened')){t821_fadeOut(menu,300);burger.classList.remove('t821_opened')}else{t821_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t821_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu.style.opacity)menu.style.opacity='';if(menu.style.display==='none')menu.style.display=''}else{if(menu.style.transform)menu.style.transform=''}},200))}
function t821_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t821_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t858_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t858');if(!container)return;t858_unifyHeights(recId);window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t858_unifyHeights(recId)}));window.addEventListener('load',function(){t858_unifyHeights(recId)});if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t858_unifyHeights(recId)})}else{container.addEventListener('displayChanged',function(){t858_unifyHeights(recId)})}
if(container.classList.contains('t858__previewmode')){setInterval(function(){t858_unifyHeights(recId)},5000)}}
function t858_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t858');if(!container)return;if(window.innerWidth>=960){var rows=container.querySelectorAll('.t858__row');for(var i=0;i<rows.length;i++){var row=rows[i];var maxHeight=0;var cols=row.querySelectorAll('.t858__inner-col');for(var j=0;j<cols.length;j++){var col=cols[j];var colWrap=col.querySelector('.t858__wrap');var colHeight=colWrap.offsetHeight;if(colHeight>maxHeight)maxHeight=colHeight}
for(var j=0;j<cols.length;j++){cols[j].style.height=maxHeight+'px'}}}else{var cols=rec.querySelectorAll('.t858__inner-col');for(var i=0;i<cols.length;i++){cols[i].style.height='auto'}}}
function t972_init(recid){if(t972_getCookie('t_cookiesConsentGiven')){t972_acceptCookies();return}else{var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;wrapper.classList.remove('t972_closed');t972_addEvents(recid);t972_addCookieEvents(recid);t972_translateToggle(recid)}}
function t972_initPreview(recid){t972_addEvents(recid);t972_translateToggle(recid)}
function t972_getCookie(name){var matches=document.cookie.match(new RegExp('(?:^|; )'+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+'=([^;]*)'));var cookie=matches?{name:name,val:decodeURIComponent(matches[1])}:null;return cookie}
function t972_createCookie(name,value,days){var expires;if(days){var date=new Date();var dayInMs=24*60*60*1000;date.setTime(date.getTime()+days*dayInMs);expires='; expires='+date.toGMTString()}else{expires=''}
document.cookie=name+'='+value+expires+'; path=/'}
function t972_confirmCookies(list){var checkBoxes=document.querySelectorAll('.t972__categories input[name="cookie_type"]');var selectedCookies=[];if(list==='all'){Array.prototype.forEach.call(checkBoxes,function(checkBox){checkBox.checked=!0})}
Array.prototype.forEach.call(checkBoxes,function(checkBox){if(checkBox.checked===!0){selectedCookies.push(checkBox.value)}});var allowedCookiesList=JSON.stringify(selectedCookies);t972_createCookie('t_cookiesCategories',allowedCookiesList,365);t972_acceptCookies()}
function t972_acceptCookies(){var allowedCookiesList=t972_getCookie('t_cookiesCategories').val;var scriptsList=document.querySelectorAll('script[data-tilda-cookie-type]');Array.prototype.forEach.call(scriptsList,function(item){if(allowedCookiesList.indexOf(item.getAttribute('data-tilda-cookie-type'))!==-1){if(item.getAttribute('type')&&item.getAttribute('type')==='text/plain'){var str=item.innerHTML;item.innerHTML='';item.setAttribute('type','text/javascript');item.innerHTML=str.replace('}, 2000);','}, 200);');if(allowedCookiesList.indexOf('advertising')==-1){if(str.indexOf('google-analytics')!==-1){item.innerHTML=str.replace('auto','{ storeGac: false }')}}
if(allowedCookiesList.indexOf('analytics')!==-1){if(typeof tildastat=='function'){tildastat('cookieenabled')}else{setTimeout(function(){if(typeof tildastat=='function'){tildastat('cookieenabled')}},1000)}}
item.setAttribute('data-tilda-cookie-consent','accepted')}
if(item.getAttribute('data-src')){item.setAttribute('src',item.getAttribute('data-src'));item.setAttribute('data-tilda-cookie-consent','accepted')}}});t972_createCookie('t_cookiesConsentGiven','true',365)}
function t972_addEvents(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;var settingsBtn=wrapper.querySelector('.t972__settings-btn');var settingsHeader=wrapper.querySelector('.t972__settings-header');var categoryTitle=wrapper.querySelectorAll('.t972__category-header');var categoryToggle=wrapper.querySelectorAll('.t972__toggle-input');var cookiesBanner=wrapper.querySelector('.t972__banner');var settingsBanner=wrapper.querySelector('.t972__settings');settingsBtn.addEventListener('click',function(){cookiesBanner.style.display='none';settingsBanner.style.display='flex'});settingsHeader.addEventListener('click',function(){cookiesBanner.style.display='block';settingsBanner.style.display='none'});Array.prototype.forEach.call(categoryTitle,function(title){title.addEventListener('click',function(){var categoryBody=title.closest('.t972__category').querySelector('.t972__category-body');title.classList.toggle('t972__opened');title.style.pointerEvents='none';t972_slideToggle(categoryBody,title,300)})});Array.prototype.forEach.call(categoryToggle,function(toggle){toggle.addEventListener('change',function(){var toggleText=toggle.closest('.t972__category-toggle').querySelector('.t972__toggle-txt');if(toggle.checked){toggleText.classList.add('t972__category-enabled');toggleText.textContent=t972_trans('enabled')}else{toggleText.classList.remove('t972__category-enabled');toggleText.textContent=t972_trans('disabled')}})})}
function t972_slideToggle(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=500;if(window.getComputedStyle(target).display==='none'){return t972_slideDown(target,triggerElement,duration)}else{return t972_slideUp(target,triggerElement,duration)}}
function t972_slideUp(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=500;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t972_slideDown(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=500;target.style.display='';var cashedDisplay=window.getComputedStyle(target).display;if(cashedDisplay==='none')cashedDisplay='block';target.style.display=cashedDisplay;var targetHeight=target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';target.offsetHeight;target.style.boxSizing='border-box';target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.height=targetHeight+'px';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.height='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t972_addCookieEvents(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;var confirmBtn=wrapper.querySelector('.t972__confirm-btn');var acceptBtn=wrapper.querySelector('.t972__accept-btn');var cookiesBanner=wrapper.querySelector('.t972__banner');var settingsBanner=wrapper.querySelector('.t972__settings');confirmBtn.addEventListener('click',function(){t972_confirmCookies('selected');cookiesBanner.style.display='none';settingsBanner.style.display='none'});acceptBtn.addEventListener('click',function(){t972_confirmCookies('all');cookiesBanner.style.display='none';settingsBanner.style.display='none'})}
function t972_translateToggle(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t972');if(!wrapper)return;var category=wrapper.querySelectorAll('.t972__category-toggle');Array.prototype.forEach.call(category,function(cat){var categoryText=cat.querySelectorAll('.t972__toggle-txt');Array.prototype.forEach.call(categoryText,function(item){if(item.classList.contains('js_always-enabled')){item.textContent=t972_trans('alwaysEnabled')}else{var itemParent=item.parentNode;var categoryInput=itemParent.querySelector('.t972__toggle-input');if(categoryInput.checked){item.textContent=t972_trans('enabled')}else{item.textContent=t972_trans('disabled')}}})})}
function t972_trans(key){var data={alwaysEnabled:{EN:'Always Enabled',RU:'Всегда разрешено',FR:'Toujours actif',DE:'Immer aktiv',ES:'Activas siempre',PT:'Sempre ativos',JA:'常にアクティブ',ZH:'始終啟用',UK:'Завжди дозволено',PL:'Zawsze aktywne',KK:'Әрқашан қосылады',IT:'Sempre attivi',LV:'Vienmēr iespējots',},enabled:{EN:'Enabled',RU:'Разрешено',FR:'Actif',DE:'Aktiv',ES:'Activas',PT:'Ativos',JA:'アクティブ',ZH:'启用',UK:'Дозволено',PL:'Aktywne',KK:'Қосылды',IT:'Attivi',LV:'Iespējots',},disabled:{EN:'Disabled',RU:'Запрещено',FR:'Désactivé',DE:'Inaktiv',ES:'Discapacitado',PT:'Desativado',JA:'オフにした',ZH:'已禁用',UK:'Вимкнено',PL:'Wyłączone',KK:'Өшірілген',IT:'Disabilitato',LV:'Atspējots',},};var lang=window.browserLang.toUpperCase();return lang&&data[key][lang]?data[key][lang]:data[key].EN}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}